# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/templateProject1
    username: postgres
    password: 123456

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: logcenter
    generate-ddl: true

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

security.basic.enabled: false

#server.port: 8090
pac4j:
    logout:
        defaultUrl: /?defaulturlafterlogout
        destroySession: false

    callback:
        multiProfile: false

    centralLogout:
        defaultUrl: http://localhost:8090/?defaulturlafterlogoutafteridp
        logoutUrlPattern: http://localhost:8090/.*

salt: 12345678901234567890123456789012